<?php

namespace ClientBundle\Repository;

/**
 * ClienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienRepository extends \Doctrine\ORM\EntityRepository
{
}
